name: Sync to Public Repo

on:
  push:
    branches:
      - opensource
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUBLIC_REPO_PAT }}  # Use the PAT for checkout

    - name: Set up Git
      run: |
        git config --global user.name "arhamkhnz"
        git config --global user.email "md.arhamkhan09@gmail.com"

    - name: Add public repository as remote
      run: |
        git remote add public https://github.com/arhamkhnz/next-shadcn-admin-dashboard.git
        git fetch public

    - name: Pull latest changes from remote
      run: |
        git pull public main --rebase  # Pull the latest changes and rebase

    - name: Push changes to public repository
      run: |
        git push public HEAD:main  # Adjust the branch name as needed
